insert into category (description) values ('American');
insert into category (description) values ('Italian');
insert into category (description) values ('Mexican');
insert into category (description) values ('Fastfood');
insert into category (description) values ('BBQ');
insert into category (description) values ('Asian');
insert into unit_of_measure(description) values ('Teaspoon');
insert into unit_of_measure(description) values ('Tablespoon');
insert into unit_of_measure(description) values ('Cup');
insert into unit_of_measure(description) values ('Pinch');
insert into unit_of_measure(description) values ('Ounce');