insert into category (description) values ('American');
insert into category (description) values ('Italian');
insert into category (description) values ('Mexican');
insert into category (description) values ('Fastfood');
insert into category (description) values ('BBQ');
insert into category (description) values ('Asian');
insert into unit_of_measure(description) values ('each');
insert into unit_of_measure(description) values ('teaspoon');
insert into unit_of_measure(description) values ('tablespoon');
insert into unit_of_measure(description) values ('cup');
insert into unit_of_measure(description) values ('pinch');
insert into unit_of_measure(description) values ('ounce');
insert into unit_of_measure(description) values ('dash');
